name: Lighthouse

on:
  pull_request:
    branches:
      - master

jobs:
  lighthouse:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v7

      - name: Setup node env 🏗
        uses: actions/setup-node@v7
        with:
          node-version: 24
          check-latest: true

      - name: Cache node_modules 📦
        uses: actions/cache@v6
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies 👨🏻‍💻
        run: npm install --prefer-offline --no-audit

      - name: Run lighthouse mobile audit 📱
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
        run: npm run lhci:mobile

      - name: Run lighthouse desktop audit 🖥️
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
        run: npm run lhci:desktop
